// flow-typed signature: e3ee094150f650840b43020edd959b21
// flow-typed version: <<STUB>>/babel-plugin-array-last-index_v0.0.4/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-array-last-index'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-array-last-index' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-array-last-index/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-array-last-index/src/index' {
  declare module.exports: $Exports<'babel-plugin-array-last-index/src'>;
}
declare module 'babel-plugin-array-last-index/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-array-last-index/src'>;
}
