// flow-typed signature: e48be7225c75a1571853a16ad3617bfe
// flow-typed version: <<STUB>>/jsonld_v^2.0.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonld'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonld' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonld/dist/jsonld' {
  declare module.exports: any;
}

declare module 'jsonld/dist/jsonld.min' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/compact' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/constants' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/context' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/ContextResolver' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/documentLoaders/node' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/documentLoaders/xhr' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/expand' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/flatten' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/frame' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/fromRdf' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/graphTypes' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/jsonld' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/JsonLdError' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/JsonLdProcessor' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/nodeMap' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/NQuads' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/Rdfa' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/RequestQueue' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/ResolvedContext' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/toRdf' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/types' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/url' {
  declare module.exports: any;
}

declare module 'jsonld/dist/node6/lib/util' {
  declare module.exports: any;
}

declare module 'jsonld/lib/compact' {
  declare module.exports: any;
}

declare module 'jsonld/lib/constants' {
  declare module.exports: any;
}

declare module 'jsonld/lib/context' {
  declare module.exports: any;
}

declare module 'jsonld/lib/ContextResolver' {
  declare module.exports: any;
}

declare module 'jsonld/lib/documentLoaders/node' {
  declare module.exports: any;
}

declare module 'jsonld/lib/documentLoaders/xhr' {
  declare module.exports: any;
}

declare module 'jsonld/lib/expand' {
  declare module.exports: any;
}

declare module 'jsonld/lib/flatten' {
  declare module.exports: any;
}

declare module 'jsonld/lib/frame' {
  declare module.exports: any;
}

declare module 'jsonld/lib/fromRdf' {
  declare module.exports: any;
}

declare module 'jsonld/lib/graphTypes' {
  declare module.exports: any;
}

declare module 'jsonld/lib' {
  declare module.exports: any;
}

declare module 'jsonld/lib/jsonld' {
  declare module.exports: any;
}

declare module 'jsonld/lib/JsonLdError' {
  declare module.exports: any;
}

declare module 'jsonld/lib/JsonLdProcessor' {
  declare module.exports: any;
}

declare module 'jsonld/lib/nodeMap' {
  declare module.exports: any;
}

declare module 'jsonld/lib/NQuads' {
  declare module.exports: any;
}

declare module 'jsonld/lib/Rdfa' {
  declare module.exports: any;
}

declare module 'jsonld/lib/RequestQueue' {
  declare module.exports: any;
}

declare module 'jsonld/lib/ResolvedContext' {
  declare module.exports: any;
}

declare module 'jsonld/lib/toRdf' {
  declare module.exports: any;
}

declare module 'jsonld/lib/types' {
  declare module.exports: any;
}

declare module 'jsonld/lib/url' {
  declare module.exports: any;
}

declare module 'jsonld/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonld/dist/jsonld.js' {
  declare module.exports: $Exports<'jsonld/dist/jsonld'>;
}
declare module 'jsonld/dist/jsonld.min.js' {
  declare module.exports: $Exports<'jsonld/dist/jsonld.min'>;
}
declare module 'jsonld/dist/node6/lib/compact.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/compact'>;
}
declare module 'jsonld/dist/node6/lib/constants.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/constants'>;
}
declare module 'jsonld/dist/node6/lib/context.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/context'>;
}
declare module 'jsonld/dist/node6/lib/ContextResolver.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/ContextResolver'>;
}
declare module 'jsonld/dist/node6/lib/documentLoaders/node.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/documentLoaders/node'>;
}
declare module 'jsonld/dist/node6/lib/documentLoaders/xhr.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/documentLoaders/xhr'>;
}
declare module 'jsonld/dist/node6/lib/expand.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/expand'>;
}
declare module 'jsonld/dist/node6/lib/flatten.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/flatten'>;
}
declare module 'jsonld/dist/node6/lib/frame.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/frame'>;
}
declare module 'jsonld/dist/node6/lib/fromRdf.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/fromRdf'>;
}
declare module 'jsonld/dist/node6/lib/graphTypes.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/graphTypes'>;
}
declare module 'jsonld/dist/node6/lib/index' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib'>;
}
declare module 'jsonld/dist/node6/lib/index.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib'>;
}
declare module 'jsonld/dist/node6/lib/jsonld.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/jsonld'>;
}
declare module 'jsonld/dist/node6/lib/JsonLdError.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/JsonLdError'>;
}
declare module 'jsonld/dist/node6/lib/JsonLdProcessor.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/JsonLdProcessor'>;
}
declare module 'jsonld/dist/node6/lib/nodeMap.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/nodeMap'>;
}
declare module 'jsonld/dist/node6/lib/NQuads.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/NQuads'>;
}
declare module 'jsonld/dist/node6/lib/Rdfa.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/Rdfa'>;
}
declare module 'jsonld/dist/node6/lib/RequestQueue.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/RequestQueue'>;
}
declare module 'jsonld/dist/node6/lib/ResolvedContext.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/ResolvedContext'>;
}
declare module 'jsonld/dist/node6/lib/toRdf.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/toRdf'>;
}
declare module 'jsonld/dist/node6/lib/types.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/types'>;
}
declare module 'jsonld/dist/node6/lib/url.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/url'>;
}
declare module 'jsonld/dist/node6/lib/util.js' {
  declare module.exports: $Exports<'jsonld/dist/node6/lib/util'>;
}
declare module 'jsonld/lib/compact.js' {
  declare module.exports: $Exports<'jsonld/lib/compact'>;
}
declare module 'jsonld/lib/constants.js' {
  declare module.exports: $Exports<'jsonld/lib/constants'>;
}
declare module 'jsonld/lib/context.js' {
  declare module.exports: $Exports<'jsonld/lib/context'>;
}
declare module 'jsonld/lib/ContextResolver.js' {
  declare module.exports: $Exports<'jsonld/lib/ContextResolver'>;
}
declare module 'jsonld/lib/documentLoaders/node.js' {
  declare module.exports: $Exports<'jsonld/lib/documentLoaders/node'>;
}
declare module 'jsonld/lib/documentLoaders/xhr.js' {
  declare module.exports: $Exports<'jsonld/lib/documentLoaders/xhr'>;
}
declare module 'jsonld/lib/expand.js' {
  declare module.exports: $Exports<'jsonld/lib/expand'>;
}
declare module 'jsonld/lib/flatten.js' {
  declare module.exports: $Exports<'jsonld/lib/flatten'>;
}
declare module 'jsonld/lib/frame.js' {
  declare module.exports: $Exports<'jsonld/lib/frame'>;
}
declare module 'jsonld/lib/fromRdf.js' {
  declare module.exports: $Exports<'jsonld/lib/fromRdf'>;
}
declare module 'jsonld/lib/graphTypes.js' {
  declare module.exports: $Exports<'jsonld/lib/graphTypes'>;
}
declare module 'jsonld/lib/index' {
  declare module.exports: $Exports<'jsonld/lib'>;
}
declare module 'jsonld/lib/index.js' {
  declare module.exports: $Exports<'jsonld/lib'>;
}
declare module 'jsonld/lib/jsonld.js' {
  declare module.exports: $Exports<'jsonld/lib/jsonld'>;
}
declare module 'jsonld/lib/JsonLdError.js' {
  declare module.exports: $Exports<'jsonld/lib/JsonLdError'>;
}
declare module 'jsonld/lib/JsonLdProcessor.js' {
  declare module.exports: $Exports<'jsonld/lib/JsonLdProcessor'>;
}
declare module 'jsonld/lib/nodeMap.js' {
  declare module.exports: $Exports<'jsonld/lib/nodeMap'>;
}
declare module 'jsonld/lib/NQuads.js' {
  declare module.exports: $Exports<'jsonld/lib/NQuads'>;
}
declare module 'jsonld/lib/Rdfa.js' {
  declare module.exports: $Exports<'jsonld/lib/Rdfa'>;
}
declare module 'jsonld/lib/RequestQueue.js' {
  declare module.exports: $Exports<'jsonld/lib/RequestQueue'>;
}
declare module 'jsonld/lib/ResolvedContext.js' {
  declare module.exports: $Exports<'jsonld/lib/ResolvedContext'>;
}
declare module 'jsonld/lib/toRdf.js' {
  declare module.exports: $Exports<'jsonld/lib/toRdf'>;
}
declare module 'jsonld/lib/types.js' {
  declare module.exports: $Exports<'jsonld/lib/types'>;
}
declare module 'jsonld/lib/url.js' {
  declare module.exports: $Exports<'jsonld/lib/url'>;
}
declare module 'jsonld/lib/util.js' {
  declare module.exports: $Exports<'jsonld/lib/util'>;
}
