// flow-typed signature: 0669a9d0b78716b3d0a0136347afe177
// flow-typed version: <<STUB>>/n3_v^1.1.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'n3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'n3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'n3/lib/IRIs' {
  declare module.exports: any;
}

declare module 'n3/lib/N3DataFactory' {
  declare module.exports: any;
}

declare module 'n3/lib/N3Lexer' {
  declare module.exports: any;
}

declare module 'n3/lib/N3Parser' {
  declare module.exports: any;
}

declare module 'n3/lib/N3Store' {
  declare module.exports: any;
}

declare module 'n3/lib/N3StreamParser' {
  declare module.exports: any;
}

declare module 'n3/lib/N3StreamWriter' {
  declare module.exports: any;
}

declare module 'n3/lib/N3Util' {
  declare module.exports: any;
}

declare module 'n3/lib/N3Writer' {
  declare module.exports: any;
}

declare module 'n3/N3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'n3/lib/IRIs.js' {
  declare module.exports: $Exports<'n3/lib/IRIs'>;
}
declare module 'n3/lib/N3DataFactory.js' {
  declare module.exports: $Exports<'n3/lib/N3DataFactory'>;
}
declare module 'n3/lib/N3Lexer.js' {
  declare module.exports: $Exports<'n3/lib/N3Lexer'>;
}
declare module 'n3/lib/N3Parser.js' {
  declare module.exports: $Exports<'n3/lib/N3Parser'>;
}
declare module 'n3/lib/N3Store.js' {
  declare module.exports: $Exports<'n3/lib/N3Store'>;
}
declare module 'n3/lib/N3StreamParser.js' {
  declare module.exports: $Exports<'n3/lib/N3StreamParser'>;
}
declare module 'n3/lib/N3StreamWriter.js' {
  declare module.exports: $Exports<'n3/lib/N3StreamWriter'>;
}
declare module 'n3/lib/N3Util.js' {
  declare module.exports: $Exports<'n3/lib/N3Util'>;
}
declare module 'n3/lib/N3Writer.js' {
  declare module.exports: $Exports<'n3/lib/N3Writer'>;
}
declare module 'n3/N3.js' {
  declare module.exports: $Exports<'n3/N3'>;
}
