// flow-typed signature: ab3c37be391e774b40f91799a9a89803
// flow-typed version: <<STUB>>/path-browserify_v^1.0.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'path-browserify/test' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-basename' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-dirname' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-extname' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-isabsolute' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-join' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-parse-format' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-relative' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-resolve' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path-zero-length-strings' {
  declare module.exports: any;
}

declare module 'path-browserify/test/test-path' {
  declare module.exports: any;
}

// Filename aliases
declare module 'path-browserify/index' {
  declare module.exports: $Exports<'path-browserify'>;
}
declare module 'path-browserify/index.js' {
  declare module.exports: $Exports<'path-browserify'>;
}
declare module 'path-browserify/test/index' {
  declare module.exports: $Exports<'path-browserify/test'>;
}
declare module 'path-browserify/test/index.js' {
  declare module.exports: $Exports<'path-browserify/test'>;
}
declare module 'path-browserify/test/test-path-basename.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-basename'>;
}
declare module 'path-browserify/test/test-path-dirname.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-dirname'>;
}
declare module 'path-browserify/test/test-path-extname.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-extname'>;
}
declare module 'path-browserify/test/test-path-isabsolute.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-isabsolute'>;
}
declare module 'path-browserify/test/test-path-join.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-join'>;
}
declare module 'path-browserify/test/test-path-parse-format.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-parse-format'>;
}
declare module 'path-browserify/test/test-path-relative.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-relative'>;
}
declare module 'path-browserify/test/test-path-resolve.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-resolve'>;
}
declare module 'path-browserify/test/test-path-zero-length-strings.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path-zero-length-strings'>;
}
declare module 'path-browserify/test/test-path.js' {
  declare module.exports: $Exports<'path-browserify/test/test-path'>;
}
