// flow-typed signature: 1f42dbcb933f9e580357e7fc214cd363
// flow-typed version: <<STUB>>/promise.allsettled_v^1.0.2/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise.allsettled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise.allsettled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise.allsettled/auto' {
  declare module.exports: any;
}

declare module 'promise.allsettled/implementation' {
  declare module.exports: any;
}

declare module 'promise.allsettled/polyfill' {
  declare module.exports: any;
}

declare module 'promise.allsettled/requirePromise' {
  declare module.exports: any;
}

declare module 'promise.allsettled/shim' {
  declare module.exports: any;
}

declare module 'promise.allsettled/test/builtin' {
  declare module.exports: any;
}

declare module 'promise.allsettled/test' {
  declare module.exports: any;
}

declare module 'promise.allsettled/test/native' {
  declare module.exports: any;
}

declare module 'promise.allsettled/test/promise-shimmed' {
  declare module.exports: any;
}

declare module 'promise.allsettled/test/shimmed' {
  declare module.exports: any;
}

declare module 'promise.allsettled/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise.allsettled/auto.js' {
  declare module.exports: $Exports<'promise.allsettled/auto'>;
}
declare module 'promise.allsettled/implementation.js' {
  declare module.exports: $Exports<'promise.allsettled/implementation'>;
}
declare module 'promise.allsettled/index' {
  declare module.exports: $Exports<'promise.allsettled'>;
}
declare module 'promise.allsettled/index.js' {
  declare module.exports: $Exports<'promise.allsettled'>;
}
declare module 'promise.allsettled/polyfill.js' {
  declare module.exports: $Exports<'promise.allsettled/polyfill'>;
}
declare module 'promise.allsettled/requirePromise.js' {
  declare module.exports: $Exports<'promise.allsettled/requirePromise'>;
}
declare module 'promise.allsettled/shim.js' {
  declare module.exports: $Exports<'promise.allsettled/shim'>;
}
declare module 'promise.allsettled/test/builtin.js' {
  declare module.exports: $Exports<'promise.allsettled/test/builtin'>;
}
declare module 'promise.allsettled/test/index' {
  declare module.exports: $Exports<'promise.allsettled/test'>;
}
declare module 'promise.allsettled/test/index.js' {
  declare module.exports: $Exports<'promise.allsettled/test'>;
}
declare module 'promise.allsettled/test/native.js' {
  declare module.exports: $Exports<'promise.allsettled/test/native'>;
}
declare module 'promise.allsettled/test/promise-shimmed.js' {
  declare module.exports: $Exports<'promise.allsettled/test/promise-shimmed'>;
}
declare module 'promise.allsettled/test/shimmed.js' {
  declare module.exports: $Exports<'promise.allsettled/test/shimmed'>;
}
declare module 'promise.allsettled/test/tests.js' {
  declare module.exports: $Exports<'promise.allsettled/test/tests'>;
}
