// flow-typed signature: 3b36136ea668c3a185a44e89271a060e
// flow-typed version: <<STUB>>/rdf-translator_v^2.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rdf-translator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rdf-translator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rdf-translator/index.es5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rdf-translator/index.es5.js' {
  declare module.exports: $Exports<'rdf-translator/index.es5'>;
}
