// flow-typed signature: 949bf28b3edd9b249d7fe25a040a11c6
// flow-typed version: <<STUB>>/solid-server_v^5.2.2/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'solid-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'solid-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'solid-server/bin/lib/cli-utils' {
  declare module.exports: any;
}

declare module 'solid-server/bin/lib/cli' {
  declare module.exports: any;
}

declare module 'solid-server/bin/lib/init' {
  declare module.exports: any;
}

declare module 'solid-server/bin/lib/invalidUsernames' {
  declare module.exports: any;
}

declare module 'solid-server/bin/lib/migrateLegacyResources' {
  declare module.exports: any;
}

declare module 'solid-server/bin/lib/options' {
  declare module.exports: any;
}

declare module 'solid-server/bin/lib/start' {
  declare module.exports: any;
}

declare module 'solid-server/bin/lib/updateIndex' {
  declare module.exports: any;
}

declare module 'solid-server/bin/solid' {
  declare module.exports: any;
}

declare module 'solid-server/common/js/auth-buttons' {
  declare module.exports: any;
}

declare module 'solid-server/common/js/solid' {
  declare module.exports: any;
}

declare module 'solid-server/config/defaults' {
  declare module.exports: any;
}

declare module 'solid-server/default-templates/emails/delete-account' {
  declare module.exports: any;
}

declare module 'solid-server/default-templates/emails/invalid-username' {
  declare module.exports: any;
}

declare module 'solid-server/default-templates/emails/reset-password' {
  declare module.exports: any;
}

declare module 'solid-server/default-templates/emails/welcome' {
  declare module.exports: any;
}

declare module 'solid-server/examples/custom-error-handling' {
  declare module.exports: any;
}

declare module 'solid-server/examples/ldp-with-webid' {
  declare module.exports: any;
}

declare module 'solid-server/examples/simple-express-app' {
  declare module.exports: any;
}

declare module 'solid-server/examples/simple-ldp-server' {
  declare module.exports: any;
}

declare module 'solid-server/lib/acl-checker' {
  declare module.exports: any;
}

declare module 'solid-server/lib/api/accounts/user-accounts' {
  declare module.exports: any;
}

declare module 'solid-server/lib/api/authn/force-user' {
  declare module.exports: any;
}

declare module 'solid-server/lib/api/authn' {
  declare module.exports: any;
}

declare module 'solid-server/lib/api/authn/webid-oidc' {
  declare module.exports: any;
}

declare module 'solid-server/lib/api/authn/webid-tls' {
  declare module.exports: any;
}

declare module 'solid-server/lib/api' {
  declare module.exports: any;
}

declare module 'solid-server/lib/capability-discovery' {
  declare module.exports: any;
}

declare module 'solid-server/lib/common/fs-utils' {
  declare module.exports: any;
}

declare module 'solid-server/lib/common/template-utils' {
  declare module.exports: any;
}

declare module 'solid-server/lib/common/user-utils' {
  declare module.exports: any;
}

declare module 'solid-server/lib/create-app' {
  declare module.exports: any;
}

declare module 'solid-server/lib/create-server' {
  declare module.exports: any;
}

declare module 'solid-server/lib/debug' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/allow' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/auth-proxy' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/copy' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/cors-proxy' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/delete' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/error-pages' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/get' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/options' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/patch' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/patch/n3-patch-parser' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/patch/sparql-update-parser' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/post' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/put' {
  declare module.exports: any;
}

declare module 'solid-server/lib/handlers/restrict-to-top-domain' {
  declare module.exports: any;
}

declare module 'solid-server/lib/header' {
  declare module.exports: any;
}

declare module 'solid-server/lib/http-error' {
  declare module.exports: any;
}

declare module 'solid-server/lib/ldp-container' {
  declare module.exports: any;
}

declare module 'solid-server/lib/ldp-copy' {
  declare module.exports: any;
}

declare module 'solid-server/lib/ldp-middleware' {
  declare module.exports: any;
}

declare module 'solid-server/lib/ldp' {
  declare module.exports: any;
}

declare module 'solid-server/lib/lock' {
  declare module.exports: any;
}

declare module 'solid-server/lib/metadata' {
  declare module.exports: any;
}

declare module 'solid-server/lib/models/account-manager' {
  declare module.exports: any;
}

declare module 'solid-server/lib/models/account-template' {
  declare module.exports: any;
}

declare module 'solid-server/lib/models/authenticator' {
  declare module.exports: any;
}

declare module 'solid-server/lib/models/oidc-manager' {
  declare module.exports: any;
}

declare module 'solid-server/lib/models/solid-host' {
  declare module.exports: any;
}

declare module 'solid-server/lib/models/user-account' {
  declare module.exports: any;
}

declare module 'solid-server/lib/models/webid-tls-certificate' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/add-cert-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/auth-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/create-account-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/delete-account-confirm-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/delete-account-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/login-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/password-change-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/password-reset-email-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/requests/sharing-request' {
  declare module.exports: any;
}

declare module 'solid-server/lib/resource-mapper' {
  declare module.exports: any;
}

declare module 'solid-server/lib/server-config' {
  declare module.exports: any;
}

declare module 'solid-server/lib/services/blacklist-service' {
  declare module.exports: any;
}

declare module 'solid-server/lib/services/email-service' {
  declare module.exports: any;
}

declare module 'solid-server/lib/services/token-service' {
  declare module.exports: any;
}

declare module 'solid-server/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'solid-server/bin/lib/cli-utils.js' {
  declare module.exports: $Exports<'solid-server/bin/lib/cli-utils'>;
}
declare module 'solid-server/bin/lib/cli.js' {
  declare module.exports: $Exports<'solid-server/bin/lib/cli'>;
}
declare module 'solid-server/bin/lib/init.js' {
  declare module.exports: $Exports<'solid-server/bin/lib/init'>;
}
declare module 'solid-server/bin/lib/invalidUsernames.js' {
  declare module.exports: $Exports<'solid-server/bin/lib/invalidUsernames'>;
}
declare module 'solid-server/bin/lib/migrateLegacyResources.js' {
  declare module.exports: $Exports<'solid-server/bin/lib/migrateLegacyResources'>;
}
declare module 'solid-server/bin/lib/options.js' {
  declare module.exports: $Exports<'solid-server/bin/lib/options'>;
}
declare module 'solid-server/bin/lib/start.js' {
  declare module.exports: $Exports<'solid-server/bin/lib/start'>;
}
declare module 'solid-server/bin/lib/updateIndex.js' {
  declare module.exports: $Exports<'solid-server/bin/lib/updateIndex'>;
}
declare module 'solid-server/bin/solid.js' {
  declare module.exports: $Exports<'solid-server/bin/solid'>;
}
declare module 'solid-server/common/js/auth-buttons.js' {
  declare module.exports: $Exports<'solid-server/common/js/auth-buttons'>;
}
declare module 'solid-server/common/js/solid.js' {
  declare module.exports: $Exports<'solid-server/common/js/solid'>;
}
declare module 'solid-server/config/defaults.js' {
  declare module.exports: $Exports<'solid-server/config/defaults'>;
}
declare module 'solid-server/default-templates/emails/delete-account.js' {
  declare module.exports: $Exports<'solid-server/default-templates/emails/delete-account'>;
}
declare module 'solid-server/default-templates/emails/invalid-username.js' {
  declare module.exports: $Exports<'solid-server/default-templates/emails/invalid-username'>;
}
declare module 'solid-server/default-templates/emails/reset-password.js' {
  declare module.exports: $Exports<'solid-server/default-templates/emails/reset-password'>;
}
declare module 'solid-server/default-templates/emails/welcome.js' {
  declare module.exports: $Exports<'solid-server/default-templates/emails/welcome'>;
}
declare module 'solid-server/examples/custom-error-handling.js' {
  declare module.exports: $Exports<'solid-server/examples/custom-error-handling'>;
}
declare module 'solid-server/examples/ldp-with-webid.js' {
  declare module.exports: $Exports<'solid-server/examples/ldp-with-webid'>;
}
declare module 'solid-server/examples/simple-express-app.js' {
  declare module.exports: $Exports<'solid-server/examples/simple-express-app'>;
}
declare module 'solid-server/examples/simple-ldp-server.js' {
  declare module.exports: $Exports<'solid-server/examples/simple-ldp-server'>;
}
declare module 'solid-server/index' {
  declare module.exports: $Exports<'solid-server'>;
}
declare module 'solid-server/index.js' {
  declare module.exports: $Exports<'solid-server'>;
}
declare module 'solid-server/lib/acl-checker.js' {
  declare module.exports: $Exports<'solid-server/lib/acl-checker'>;
}
declare module 'solid-server/lib/api/accounts/user-accounts.js' {
  declare module.exports: $Exports<'solid-server/lib/api/accounts/user-accounts'>;
}
declare module 'solid-server/lib/api/authn/force-user.js' {
  declare module.exports: $Exports<'solid-server/lib/api/authn/force-user'>;
}
declare module 'solid-server/lib/api/authn/index' {
  declare module.exports: $Exports<'solid-server/lib/api/authn'>;
}
declare module 'solid-server/lib/api/authn/index.js' {
  declare module.exports: $Exports<'solid-server/lib/api/authn'>;
}
declare module 'solid-server/lib/api/authn/webid-oidc.js' {
  declare module.exports: $Exports<'solid-server/lib/api/authn/webid-oidc'>;
}
declare module 'solid-server/lib/api/authn/webid-tls.js' {
  declare module.exports: $Exports<'solid-server/lib/api/authn/webid-tls'>;
}
declare module 'solid-server/lib/api/index' {
  declare module.exports: $Exports<'solid-server/lib/api'>;
}
declare module 'solid-server/lib/api/index.js' {
  declare module.exports: $Exports<'solid-server/lib/api'>;
}
declare module 'solid-server/lib/capability-discovery.js' {
  declare module.exports: $Exports<'solid-server/lib/capability-discovery'>;
}
declare module 'solid-server/lib/common/fs-utils.js' {
  declare module.exports: $Exports<'solid-server/lib/common/fs-utils'>;
}
declare module 'solid-server/lib/common/template-utils.js' {
  declare module.exports: $Exports<'solid-server/lib/common/template-utils'>;
}
declare module 'solid-server/lib/common/user-utils.js' {
  declare module.exports: $Exports<'solid-server/lib/common/user-utils'>;
}
declare module 'solid-server/lib/create-app.js' {
  declare module.exports: $Exports<'solid-server/lib/create-app'>;
}
declare module 'solid-server/lib/create-server.js' {
  declare module.exports: $Exports<'solid-server/lib/create-server'>;
}
declare module 'solid-server/lib/debug.js' {
  declare module.exports: $Exports<'solid-server/lib/debug'>;
}
declare module 'solid-server/lib/handlers/allow.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/allow'>;
}
declare module 'solid-server/lib/handlers/auth-proxy.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/auth-proxy'>;
}
declare module 'solid-server/lib/handlers/copy.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/copy'>;
}
declare module 'solid-server/lib/handlers/cors-proxy.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/cors-proxy'>;
}
declare module 'solid-server/lib/handlers/delete.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/delete'>;
}
declare module 'solid-server/lib/handlers/error-pages.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/error-pages'>;
}
declare module 'solid-server/lib/handlers/get.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/get'>;
}
declare module 'solid-server/lib/handlers/index' {
  declare module.exports: $Exports<'solid-server/lib/handlers'>;
}
declare module 'solid-server/lib/handlers/index.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers'>;
}
declare module 'solid-server/lib/handlers/options.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/options'>;
}
declare module 'solid-server/lib/handlers/patch.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/patch'>;
}
declare module 'solid-server/lib/handlers/patch/n3-patch-parser.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/patch/n3-patch-parser'>;
}
declare module 'solid-server/lib/handlers/patch/sparql-update-parser.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/patch/sparql-update-parser'>;
}
declare module 'solid-server/lib/handlers/post.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/post'>;
}
declare module 'solid-server/lib/handlers/put.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/put'>;
}
declare module 'solid-server/lib/handlers/restrict-to-top-domain.js' {
  declare module.exports: $Exports<'solid-server/lib/handlers/restrict-to-top-domain'>;
}
declare module 'solid-server/lib/header.js' {
  declare module.exports: $Exports<'solid-server/lib/header'>;
}
declare module 'solid-server/lib/http-error.js' {
  declare module.exports: $Exports<'solid-server/lib/http-error'>;
}
declare module 'solid-server/lib/ldp-container.js' {
  declare module.exports: $Exports<'solid-server/lib/ldp-container'>;
}
declare module 'solid-server/lib/ldp-copy.js' {
  declare module.exports: $Exports<'solid-server/lib/ldp-copy'>;
}
declare module 'solid-server/lib/ldp-middleware.js' {
  declare module.exports: $Exports<'solid-server/lib/ldp-middleware'>;
}
declare module 'solid-server/lib/ldp.js' {
  declare module.exports: $Exports<'solid-server/lib/ldp'>;
}
declare module 'solid-server/lib/lock.js' {
  declare module.exports: $Exports<'solid-server/lib/lock'>;
}
declare module 'solid-server/lib/metadata.js' {
  declare module.exports: $Exports<'solid-server/lib/metadata'>;
}
declare module 'solid-server/lib/models/account-manager.js' {
  declare module.exports: $Exports<'solid-server/lib/models/account-manager'>;
}
declare module 'solid-server/lib/models/account-template.js' {
  declare module.exports: $Exports<'solid-server/lib/models/account-template'>;
}
declare module 'solid-server/lib/models/authenticator.js' {
  declare module.exports: $Exports<'solid-server/lib/models/authenticator'>;
}
declare module 'solid-server/lib/models/oidc-manager.js' {
  declare module.exports: $Exports<'solid-server/lib/models/oidc-manager'>;
}
declare module 'solid-server/lib/models/solid-host.js' {
  declare module.exports: $Exports<'solid-server/lib/models/solid-host'>;
}
declare module 'solid-server/lib/models/user-account.js' {
  declare module.exports: $Exports<'solid-server/lib/models/user-account'>;
}
declare module 'solid-server/lib/models/webid-tls-certificate.js' {
  declare module.exports: $Exports<'solid-server/lib/models/webid-tls-certificate'>;
}
declare module 'solid-server/lib/requests/add-cert-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/add-cert-request'>;
}
declare module 'solid-server/lib/requests/auth-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/auth-request'>;
}
declare module 'solid-server/lib/requests/create-account-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/create-account-request'>;
}
declare module 'solid-server/lib/requests/delete-account-confirm-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/delete-account-confirm-request'>;
}
declare module 'solid-server/lib/requests/delete-account-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/delete-account-request'>;
}
declare module 'solid-server/lib/requests/login-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/login-request'>;
}
declare module 'solid-server/lib/requests/password-change-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/password-change-request'>;
}
declare module 'solid-server/lib/requests/password-reset-email-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/password-reset-email-request'>;
}
declare module 'solid-server/lib/requests/sharing-request.js' {
  declare module.exports: $Exports<'solid-server/lib/requests/sharing-request'>;
}
declare module 'solid-server/lib/resource-mapper.js' {
  declare module.exports: $Exports<'solid-server/lib/resource-mapper'>;
}
declare module 'solid-server/lib/server-config.js' {
  declare module.exports: $Exports<'solid-server/lib/server-config'>;
}
declare module 'solid-server/lib/services/blacklist-service.js' {
  declare module.exports: $Exports<'solid-server/lib/services/blacklist-service'>;
}
declare module 'solid-server/lib/services/email-service.js' {
  declare module.exports: $Exports<'solid-server/lib/services/email-service'>;
}
declare module 'solid-server/lib/services/token-service.js' {
  declare module.exports: $Exports<'solid-server/lib/services/token-service'>;
}
declare module 'solid-server/lib/utils.js' {
  declare module.exports: $Exports<'solid-server/lib/utils'>;
}
