// flow-typed signature: 05d4b7ef5f22926d7ec8981b25bb35c5
// flow-typed version: <<STUB>>/solid-auth-client_v^2.3.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'solid-auth-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'solid-auth-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'solid-auth-client/bin/solid-auth-client' {
  declare module.exports: any;
}

declare module 'solid-auth-client/browser/index' {
  declare module.exports: any;
}

declare module 'solid-auth-client/dist-lib/solid-auth-client.bundle' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/authn-fetch' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/host' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/index-default' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/index' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/ipc' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/popup' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/session' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/solid-auth-client' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/storage' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/url-util' {
  declare module.exports: any;
}

declare module 'solid-auth-client/lib/webid-oidc' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/authn-fetch' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/host' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/index-default' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/index' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/ipc' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/popup' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/session' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/solid-auth-client' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/storage' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/url-util' {
  declare module.exports: any;
}

declare module 'solid-auth-client/module/webid-oidc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'solid-auth-client/bin/solid-auth-client.js' {
  declare module.exports: $Exports<'solid-auth-client/bin/solid-auth-client'>;
}
declare module 'solid-auth-client/browser/index.js' {
  declare module.exports: $Exports<'solid-auth-client/browser/index'>;
}
declare module 'solid-auth-client/dist-lib/solid-auth-client.bundle.js' {
  declare module.exports: $Exports<'solid-auth-client/dist-lib/solid-auth-client.bundle'>;
}
declare module 'solid-auth-client/lib/authn-fetch.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/authn-fetch'>;
}
declare module 'solid-auth-client/lib/host.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/host'>;
}
declare module 'solid-auth-client/lib/index-default.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/index-default'>;
}
declare module 'solid-auth-client/lib/index.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/index'>;
}
declare module 'solid-auth-client/lib/ipc.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/ipc'>;
}
declare module 'solid-auth-client/lib/popup.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/popup'>;
}
declare module 'solid-auth-client/lib/session.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/session'>;
}
declare module 'solid-auth-client/lib/solid-auth-client.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/solid-auth-client'>;
}
declare module 'solid-auth-client/lib/storage.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/storage'>;
}
declare module 'solid-auth-client/lib/url-util.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/url-util'>;
}
declare module 'solid-auth-client/lib/webid-oidc.js' {
  declare module.exports: $Exports<'solid-auth-client/lib/webid-oidc'>;
}
declare module 'solid-auth-client/module/authn-fetch.js' {
  declare module.exports: $Exports<'solid-auth-client/module/authn-fetch'>;
}
declare module 'solid-auth-client/module/host.js' {
  declare module.exports: $Exports<'solid-auth-client/module/host'>;
}
declare module 'solid-auth-client/module/index-default.js' {
  declare module.exports: $Exports<'solid-auth-client/module/index-default'>;
}
declare module 'solid-auth-client/module/index.js' {
  declare module.exports: $Exports<'solid-auth-client/module/index'>;
}
declare module 'solid-auth-client/module/ipc.js' {
  declare module.exports: $Exports<'solid-auth-client/module/ipc'>;
}
declare module 'solid-auth-client/module/popup.js' {
  declare module.exports: $Exports<'solid-auth-client/module/popup'>;
}
declare module 'solid-auth-client/module/session.js' {
  declare module.exports: $Exports<'solid-auth-client/module/session'>;
}
declare module 'solid-auth-client/module/solid-auth-client.js' {
  declare module.exports: $Exports<'solid-auth-client/module/solid-auth-client'>;
}
declare module 'solid-auth-client/module/storage.js' {
  declare module.exports: $Exports<'solid-auth-client/module/storage'>;
}
declare module 'solid-auth-client/module/url-util.js' {
  declare module.exports: $Exports<'solid-auth-client/module/url-util'>;
}
declare module 'solid-auth-client/module/webid-oidc.js' {
  declare module.exports: $Exports<'solid-auth-client/module/webid-oidc'>;
}
