// flow-typed signature: 539a1c0ec74a96f97b048fd5be883e18
// flow-typed version: <<STUB>>/stable-sha1_v^1.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stable-sha1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stable-sha1' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stable-sha1/browser' {
  declare module.exports: any;
}

declare module 'stable-sha1/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stable-sha1/browser.js' {
  declare module.exports: $Exports<'stable-sha1/browser'>;
}
declare module 'stable-sha1/index' {
  declare module.exports: $Exports<'stable-sha1'>;
}
declare module 'stable-sha1/index.js' {
  declare module.exports: $Exports<'stable-sha1'>;
}
declare module 'stable-sha1/test.js' {
  declare module.exports: $Exports<'stable-sha1/test'>;
}
