// flow-typed signature: ddd6cff9739cb0d9c4805aacca08ba2a
// flow-typed version: <<STUB>>/@comunica/actor-init-sparql-rdfjs_v^1.7.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@comunica/actor-init-sparql-rdfjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@comunica/actor-init-sparql-rdfjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@comunica/actor-init-sparql-rdfjs/engine-default' {
  declare module.exports: any;
}

declare module '@comunica/actor-init-sparql-rdfjs/index-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module '@comunica/actor-init-sparql-rdfjs/engine-default.js' {
  declare module.exports: $Exports<'@comunica/actor-init-sparql-rdfjs/engine-default'>;
}
declare module '@comunica/actor-init-sparql-rdfjs/index-browser.js' {
  declare module.exports: $Exports<'@comunica/actor-init-sparql-rdfjs/index-browser'>;
}
declare module '@comunica/actor-init-sparql-rdfjs/index' {
  declare module.exports: $Exports<'@comunica/actor-init-sparql-rdfjs'>;
}
declare module '@comunica/actor-init-sparql-rdfjs/index.js' {
  declare module.exports: $Exports<'@comunica/actor-init-sparql-rdfjs'>;
}
