// flow-typed signature: eccebf803db50f6f7694f3b66bd285eb
// flow-typed version: <<STUB>>/@solid/query-ldflex_v^2.8.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@solid/query-ldflex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@solid/query-ldflex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@solid/query-ldflex/browser/crypto' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/browser/process' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/browser/setImmediate' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/dist/solid-query-ldflex.bundle' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/ActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/ComunicaUpdateEngine' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/ContextResolver' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/CreateActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/DeleteActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/FindActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/SolidDeleteFunctionHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/SourcePathHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/SubjectPathResolver' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/UserPathHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/lib/util' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/ActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/ComunicaUpdateEngine' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/ContextResolver' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/CreateActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/DeleteActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/FindActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/SolidDeleteFunctionHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/SourcePathHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/SubjectPathResolver' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/UserPathHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/module/util' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/ActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/ComunicaUpdateEngine' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/ContextResolver' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/CreateActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/DeleteActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/FindActivityHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/SolidDeleteFunctionHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/SourcePathHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/SubjectPathResolver' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/UserPathHandler' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/src/util' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/webpack/webpack.common.config' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/webpack/webpack.demo.config' {
  declare module.exports: any;
}

declare module '@solid/query-ldflex/webpack/webpack.lib.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@solid/query-ldflex/browser/crypto.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/browser/crypto'>;
}
declare module '@solid/query-ldflex/browser/process.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/browser/process'>;
}
declare module '@solid/query-ldflex/browser/setImmediate.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/browser/setImmediate'>;
}
declare module '@solid/query-ldflex/dist/solid-query-ldflex.bundle.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/dist/solid-query-ldflex.bundle'>;
}
declare module '@solid/query-ldflex/lib/ActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/ActivityHandler'>;
}
declare module '@solid/query-ldflex/lib/ComunicaUpdateEngine.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/ComunicaUpdateEngine'>;
}
declare module '@solid/query-ldflex/lib/ContextResolver.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/ContextResolver'>;
}
declare module '@solid/query-ldflex/lib/CreateActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/CreateActivityHandler'>;
}
declare module '@solid/query-ldflex/lib/DeleteActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/DeleteActivityHandler'>;
}
declare module '@solid/query-ldflex/lib/FindActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/FindActivityHandler'>;
}
declare module '@solid/query-ldflex/lib/index' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib'>;
}
declare module '@solid/query-ldflex/lib/index.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib'>;
}
declare module '@solid/query-ldflex/lib/SolidDeleteFunctionHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/SolidDeleteFunctionHandler'>;
}
declare module '@solid/query-ldflex/lib/SourcePathHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/SourcePathHandler'>;
}
declare module '@solid/query-ldflex/lib/SubjectPathResolver.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/SubjectPathResolver'>;
}
declare module '@solid/query-ldflex/lib/UserPathHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/UserPathHandler'>;
}
declare module '@solid/query-ldflex/lib/util.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/lib/util'>;
}
declare module '@solid/query-ldflex/module/ActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/ActivityHandler'>;
}
declare module '@solid/query-ldflex/module/ComunicaUpdateEngine.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/ComunicaUpdateEngine'>;
}
declare module '@solid/query-ldflex/module/ContextResolver.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/ContextResolver'>;
}
declare module '@solid/query-ldflex/module/CreateActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/CreateActivityHandler'>;
}
declare module '@solid/query-ldflex/module/DeleteActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/DeleteActivityHandler'>;
}
declare module '@solid/query-ldflex/module/FindActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/FindActivityHandler'>;
}
declare module '@solid/query-ldflex/module/index' {
  declare module.exports: $Exports<'@solid/query-ldflex/module'>;
}
declare module '@solid/query-ldflex/module/index.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module'>;
}
declare module '@solid/query-ldflex/module/SolidDeleteFunctionHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/SolidDeleteFunctionHandler'>;
}
declare module '@solid/query-ldflex/module/SourcePathHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/SourcePathHandler'>;
}
declare module '@solid/query-ldflex/module/SubjectPathResolver.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/SubjectPathResolver'>;
}
declare module '@solid/query-ldflex/module/UserPathHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/UserPathHandler'>;
}
declare module '@solid/query-ldflex/module/util.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/module/util'>;
}
declare module '@solid/query-ldflex/src/ActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/ActivityHandler'>;
}
declare module '@solid/query-ldflex/src/ComunicaUpdateEngine.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/ComunicaUpdateEngine'>;
}
declare module '@solid/query-ldflex/src/ContextResolver.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/ContextResolver'>;
}
declare module '@solid/query-ldflex/src/CreateActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/CreateActivityHandler'>;
}
declare module '@solid/query-ldflex/src/DeleteActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/DeleteActivityHandler'>;
}
declare module '@solid/query-ldflex/src/FindActivityHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/FindActivityHandler'>;
}
declare module '@solid/query-ldflex/src/index' {
  declare module.exports: $Exports<'@solid/query-ldflex/src'>;
}
declare module '@solid/query-ldflex/src/index.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src'>;
}
declare module '@solid/query-ldflex/src/SolidDeleteFunctionHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/SolidDeleteFunctionHandler'>;
}
declare module '@solid/query-ldflex/src/SourcePathHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/SourcePathHandler'>;
}
declare module '@solid/query-ldflex/src/SubjectPathResolver.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/SubjectPathResolver'>;
}
declare module '@solid/query-ldflex/src/UserPathHandler.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/UserPathHandler'>;
}
declare module '@solid/query-ldflex/src/util.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/src/util'>;
}
declare module '@solid/query-ldflex/webpack/webpack.common.config.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/webpack/webpack.common.config'>;
}
declare module '@solid/query-ldflex/webpack/webpack.demo.config.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/webpack/webpack.demo.config'>;
}
declare module '@solid/query-ldflex/webpack/webpack.lib.config.js' {
  declare module.exports: $Exports<'@solid/query-ldflex/webpack/webpack.lib.config'>;
}
